apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ .Values.secrets.password }}
