apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: master
      port: {{ .Values.service.masterPort }}
      targetPort: {{ .Values.service.targetMasterPort }}
      protocol: TCP
    - name: slave
      port: {{ .Values.service.slavePort }}
      targetPort: {{ .Values.service.slavePort }}
      protocol: TCP
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
